### ISSUE TITLE
How to remap keys?

### ISSUE THREAD

**Issue by martin-braun** [hexh250786313/coc-todo-tree#1]
First of all, thanks for bringing your wonderful creation onto my radar. I recently have to deal with some projects that have so many TODO's from external teams, so that I benefit from the regex feature of this plugin to filter all my TODO's. It's such a powerful tool, but I don't know how to change the keymaps, such as `t` for toggle.

Also I think some documentation would be preferred. It took me a while to figure out `t`. It also took me a while to figure out that `hlGroup` is compatible with values listed at `:h coc-highlight`.

**Comment by hexh250786313** [comment]
Actually, the common treeview keymaps are mapped by CoC itself. See `"tree.key.toggle"` in `coc-settings.json`. It seems that many people are not very familiar with the treeview function of CoC. I thought it would be a commonly used feature, like `:CocOutline`, which I assumed to be very popular. Regarding this, I will add some brief explanations in the readme.

**Comment by martin-braun** [comment]
@hexh250786313 I was aware of the `coc-settings.json`, but I missed the fact that I could simply explore the options using the CoC suggestions, oops. Yes, under `todo-tree.` I found all those keys, but the toggle of general list was missing as you pointed out, which is to be found at `tree.key.toggle`, except its not suggested by CoC and when I try to use it, I get "Configuration property may not work as folder configuration".

Apart from these issues the binding still works. However, I cannot pick `<CR>` as a binding, because it will block the `<CR>` of this plugin to open the file in the primary buffer. `t` is kinda annoying to use, so at least I can change it to another letter. I guess there might be a binding of `tree.key.` for the open action, but it's a bummer that I cannot use `<CR>` for both. I guess this is a CoC problem and has nothing to do with your plugin?

Anyways, closing this now, thanks again.

**Comment by hexh250786313** [comment]
@martin-braun 

> I guess this is a CoC problem and has nothing to do with your plugin?

Yes, limitation from CoC. But I'm not really sure if there's a simple way to override these keymaps. I will try to figure it out in coming days.

**Comment by hexh250786313** [comment]
@martin-braun https://github.com/hexh250786313/coc-todo-tree/commit/30c0ec85de43defe7998be0b1dd647cf8a8e84e0 Custom keymap for toggle expand and jump. `:CocUpdate` and try `todo-tree.invokeKey`.
